export enum MintFormStatus {
    PAYMENT_PENDING = "PAYMENT_PENDING",
    PAYMENT_SUCCESS = "PAYMENT_SUCCESS",
    PAYMENT_EXPIRED = "PAYMENT_EXPIRED",
    FORM_SUBMITTED = "FORM_SUBMITTED",
}

export enum MintStatus {
    NOT_MINTED = "NOT_MINTED",
    MINTING = "MINTING",
    MINTED = "MINTED",
}
